name: student-offer
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - boto3
  - pip:
      - mlflow==3.3.2
      - scikit-learn
      - pandas
      - numpy
      - joblib
      - cloudpickle
